---
# Service used by Grafana as a datasource
apiVersion: v1
kind: Service
metadata:
  name: nats-surveyor-prometheus
  namespace: {{ $.Release.Namespace }}
  labels:
    app: nats-surveyor-prometheus
spec:
  selector:
    prometheus: nats-surveyor
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-surveyor-observations
  namespace: {{ $.Release.Namespace }}
data:
  test.json: {{ toJson $.Values.observations }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-surveyor
  namespace: {{ $.Release.Namespace }}
  labels:
    app: nats-surveyor
spec:
  selector:
    matchLabels:
      app: nats-surveyor
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-surveyor
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: nats-surveyor-observations
      - name: creds-volume
        secret:
          secretName: nats-creds
      containers:
      - name: nats-surveyor
        image: synadia/nats-surveyor:0.0.1-alpha4
        ports:
        - containerPort: 7777
          name: metrics
        command:
          - "/nats-surveyor"
          - "-s=nats://nats-cluster-mgmt.{{ default "nats" $.Values.natsNamespace }}.svc.cluster.local:4222"
          - "-c={{ $.Values.clusterSize | default 3 }}"
          - "-creds=/var/run/nats/secrets/sys.creds"
          - "-observe=/etc/nats/observations/"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats/observations
          - name: creds-volume
            mountPath: /var/run/nats/secrets

        # Disable all cpu limits for the server.
        #
        resources:
          requests:
            cpu: 0
---
# Service used by Prometheus Operator to find the metrics endpoint.
apiVersion: v1
kind: Service
metadata:
  name: nats-surveyor
  namespace: {{ $.Release.Namespace }}
  labels:
    app: nats-surveyor
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: nats-surveyor
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nats-surveyor
  namespace: {{ $.Release.Namespace }}
spec:
  scrapeInterval: "5s"
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: nats-surveyor
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-surveyor
  namespace: {{ $.Release.Namespace }}
  labels:
    app: nats-surveyor
spec:
  selector:
    matchLabels:
      app: nats-surveyor
  endpoints:
  - port: metrics
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-creds
  namespace: {{ $.Release.Namespace }}
data:
  sys.creds: {{ $.Values.natsCreds | b64enc }}
type: Opaque
