FROM node:8 as intermediate

RUN mkdir /usr/src/event-processor/

WORKDIR /usr/src/event-processor/
COPY ./package*.json ./
COPY .npmrc .npmrc

ARG LACUNA_REGISTRY_AUTH
RUN npm install

# https://vsupalov.com/build-docker-image-clone-private-repo-ssh-key/ - to not leak secret:
FROM node:8

COPY --from=intermediate /usr/src /usr/src
WORKDIR /usr/src/event-processor
COPY . .

EXPOSE 3000
ENTRYPOINT [ "node", "index.js", "--type=trip"]